<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chao Ding">
<meta name="author" content="Jiangran Gu">
<meta name="author" content="Peiqi Li">
<meta name="author" content="Yuhao Wang">
<meta name="author" content="Jingyi Zhou">
<meta name="dcterms.date" content="2026-08-05">

<title>Communication Apprehension and Transportation Use: A Group Synthesis of Five Research Memos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="manuscript_files/libs/quarto-html/anchor.min.js"></script>
<link href="manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_files/libs/bootstrap/bootstrap-293cc809d15782442e9b1098eedb6797.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-and-literature-review" id="toc-introduction-and-literature-review" class="nav-link active" data-scroll-target="#introduction-and-literature-review">1. Introduction and Literature Review</a>
  <ul class="collapse">
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">1.1 Research Questions</a></li>
  </ul></li>
  <li><a href="#data-and-methods" id="toc-data-and-methods" class="nav-link" data-scroll-target="#data-and-methods">2. Data and Methods</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">2.1 Data sources</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">3. Results</a>
  <ul class="collapse">
  <li><a href="#rq1-chao-public-transit-vs.-ride-share-which-does-ca-predict-more-accurately" id="toc-rq1-chao-public-transit-vs.-ride-share-which-does-ca-predict-more-accurately" class="nav-link" data-scroll-target="#rq1-chao-public-transit-vs.-ride-share-which-does-ca-predict-more-accurately">3.1 RQ1 (Chao): Public transit vs.&nbsp;ride-share — which does CA predict more accurately?</a></li>
  <li><a href="#rq2-jiangran-does-drivers-license-status-predict-communication-apprehension" id="toc-rq2-jiangran-does-drivers-license-status-predict-communication-apprehension" class="nav-link" data-scroll-target="#rq2-jiangran-does-drivers-license-status-predict-communication-apprehension">3.2 RQ2 (Jiangran): Does driver’s-license status predict communication apprehension?</a></li>
  <li><a href="#rq3-peiqi-what-visual-strategy-best-illustrates-the-catransportation-relationship" id="toc-rq3-peiqi-what-visual-strategy-best-illustrates-the-catransportation-relationship" class="nav-link" data-scroll-target="#rq3-peiqi-what-visual-strategy-best-illustrates-the-catransportation-relationship">3.3 RQ3 (Peiqi): What visual strategy best illustrates the CA–transportation relationship?</a></li>
  <li><a href="#rq4-yuhao-model-comparison-for-predicting-public-transit-use" id="toc-rq4-yuhao-model-comparison-for-predicting-public-transit-use" class="nav-link" data-scroll-target="#rq4-yuhao-model-comparison-for-predicting-public-transit-use">3.4 RQ4 (Yuhao): Model comparison for predicting public-transit use</a></li>
  <li><a href="#rq5-jingyi-do-ca-and-transportation-use-differ-by-country" id="toc-rq5-jingyi-do-ca-and-transportation-use-differ-by-country" class="nav-link" data-scroll-target="#rq5-jingyi-do-ca-and-transportation-use-differ-by-country">3.5 RQ5 (Jingyi): Do CA and transportation use differ by country?</a></li>
  </ul></li>
  <li><a href="#discussion-and-suggestions-for-next-steps" id="toc-discussion-and-suggestions-for-next-steps" class="nav-link" data-scroll-target="#discussion-and-suggestions-for-next-steps">4. Discussion and Suggestions for Next Steps</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="manuscript.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Communication Apprehension and Transportation Use: A Group Synthesis of Five Research Memos</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Chao Ding </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Wisconsin–Madison
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Jiangran Gu </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Psych 755
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Peiqi Li </p>
  </div>
  <div class="quarto-title-meta-contents">
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Yuhao Wang </p>
  </div>
  <div class="quarto-title-meta-contents">
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Jingyi Zhou </p>
  </div>
  <div class="quarto-title-meta-contents">
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-and-literature-review" class="level1">
<h1>1. Introduction and Literature Review</h1>
<p>This manuscript is our submission for the summer semester project for Psych 755 at UW–Madison. In this project, we demonstrate usage of the following tools: Python (pandas, NumPy, SciPy, and statsmodels) for data cleaning and statistical modeling, Quarto/Jupyter notebooks for literate, reproducible research reporting, Matplotlib and Seaborn for data visualization, and Git/GitHub for version control and reproducibility across a five-person team.</p>
<p>Our substantive topic is communication apprehension (CA) — the fear or anxiety a person feels, whether real or anticipated, associated with communicating with others (McCroskey, 1982). McCroskey introduced the Personal Report of Communication Apprehension (PRCA) as a self-report instrument for measuring this construct, and the 24-item revision (PRCA-24) remains the field’s standard measure (McCroskey, 1982; see also James C. McCroskey’s measurement page, jamescmccroskey.com/measures/prca24.htm). Our survey used 12 of the original items — six tapping apprehension about group discussions (Q1–Q6) and six tapping apprehension in dyadic, interpersonal conversations (Q13–Q18) — each answered on a five-point agreement scale.</p>
<p>This manuscript brings together five independently written research memos, each produced by one team member using the shared survey data (PRCAQualtricsExport_FileC.csv) and, where relevant, the linked Prolific recruitment records (PRCAProlificExport_FileA.csv and FileB.csv). Each subsection of the Results below reports that member’s own research question, method, and findings as documented in their memo.</p>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">1.1 Research Questions</h2>
<p><strong>RQ1 (Chao).</strong> Which transportation outcome does communication apprehension predict more accurately — public-transit use or ride-share use — as judged by root mean squared error (RMSE)?</p>
<p><strong>RQ2 (Jiangran).</strong> Does holding a driver’s license (Q20) predict communication apprehension?</p>
<p><strong>RQ3 (Peiqi).</strong> What visual strategy best illustrates the relationship between communication apprehension and transportation use?</p>
<p><strong>RQ4 (Yuhao).</strong> Among a simple regression on total CA, a multiple regression on the two CA subscales, and a model that adds their interaction, which model gives the lowest RMSE for predicting public-transportation use frequency?</p>
<p><strong>RQ5 (Jingyi).</strong> How do communication apprehension and public-transportation/ride-share use differ by country of residence?</p>
</section>
</section>
<section id="data-and-methods" class="level1">
<h1>2. Data and Methods</h1>
<section id="data-sources" class="level2">
<h2 class="anchored" data-anchor-id="data-sources">2.1 Data sources</h2>
<p>PRCAQualtricsExport_FileC.csv is the Qualtrics export of the PRCA-style survey: the 12 communication-apprehension items (Q1–Q6, Q13–Q18), transportation-frequency items (Q26 public-transit days per month, Q28 ride-share days per month) with matched “rides per typical day” follow-ups (Q27, Q29), driver’s-license and car-access items (Q20, Q21), and two open-ended items. PRCAProlificExport_FileA.csv and FileB.csv are Prolific platform exports covering two recruitment batches, with demographic fields including country of residence. Several memos (Chao, Jiangran, Peiqi, Yuhao) worked directly from FileC; the Jingyi memo additionally concatenated FileA and FileB and merged the result with FileC by matching each respondent’s typed Prolific ID (Q0) to their Prolific “Participant id,” in order to bring country of residence into the analysis.</p>
<p>Each team member wrote and ran their own independent data-cleaning and scoring script in their memo. As a result, the specific recoding choices — which items were treated as reverse-worded, whether the 12-item composite was formed by summing or averaging, and how missing data were handled — vary somewhat from memo to memo, and are described within each memo’s own subsection below rather than standardized across the manuscript. Reported sample sizes therefore also vary by memo (from N = 17 to N = 255), reflecting each author’s own listwise-deletion and file-loading choices.</p>
</section>
</section>
<section id="results" class="level1">
<h1>3. Results</h1>
<section id="rq1-chao-public-transit-vs.-ride-share-which-does-ca-predict-more-accurately" class="level2">
<h2 class="anchored" data-anchor-id="rq1-chao-public-transit-vs.-ride-share-which-does-ca-predict-more-accurately">3.1 RQ1 (Chao): Public transit vs.&nbsp;ride-share — which does CA predict more accurately?</h2>
<p>Method: Using PRCAQualtricsExport_FileC.csv (273 rows), the memo recoded the 12 PRCA items to a 1–5 scale, reverse-scored the positively worded items (Q2, Q4, Q6, Q14, Q16, Q17), and summed the group (Q1–Q6) and interpersonal (Q13–Q18) subscores into a 12-item composite, CA12. Public-transit (Q26) and ride-share (Q28) use were recoded to 0–4. Separate simple linear regressions were fit for each outcome on CA12, and the two models were compared by RMSE. The memo reports 17 respondents with complete CA12 scores.</p>
<div id="tbl-chao-descriptive" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-chao-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Descriptive statistics reported.
</figcaption>
<div aria-describedby="tbl-chao-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>N</th>
<th>Mean</th>
<th>SD</th>
<th>Median</th>
<th>Min</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA12</td>
<td>17</td>
<td>17.412</td>
<td>12.405</td>
<td>12.0</td>
<td>12.0</td>
<td>60.0</td>
</tr>
<tr class="even">
<td>CA_group</td>
<td>32</td>
<td>12.312</td>
<td>9.437</td>
<td>6.0</td>
<td>6.0</td>
<td>30.0</td>
</tr>
<tr class="odd">
<td>CA_interpersonal</td>
<td>28</td>
<td>9.214</td>
<td>7.104</td>
<td>6.0</td>
<td>6.0</td>
<td>30.0</td>
</tr>
<tr class="even">
<td>PT</td>
<td>271</td>
<td>2.133</td>
<td>1.460</td>
<td>2.0</td>
<td>0.0</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td>RS</td>
<td>271</td>
<td>1.506</td>
<td>1.241</td>
<td>1.0</td>
<td>0.0</td>
<td>4.0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-chao-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-chao-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Regression estimates and RMSE reported.
</figcaption>
<div aria-describedby="tbl-chao-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome</th>
<th>N</th>
<th>Intercept</th>
<th>CA12 slope</th>
<th>R²</th>
<th>p</th>
<th>RMSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Public transit</td>
<td>17</td>
<td>3.1361</td>
<td>−0.0484</td>
<td>0.1534</td>
<td>0.1200</td>
<td>1.3671</td>
</tr>
<tr class="even">
<td>Ride-share</td>
<td>17</td>
<td>2.5979</td>
<td>−0.0411</td>
<td>0.1397</td>
<td>0.1395</td>
<td>1.2273</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-chao-pt" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chao-pt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image1.png" class="img-fluid figure-img" width="525">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chao-pt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Public-transit use as a function of CA12.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-chao-rs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chao-rs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image9.png" class="img-fluid figure-img" width="525">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chao-rs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Ride-share use as a function of CA12.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-chao-rmse" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chao-rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image10.png" class="img-fluid figure-img" width="525">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chao-rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: RMSE comparison for the public-transit and ride-share models.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Direct answer: Communication apprehension predicts ride-share use more accurately under the memo’s RMSE criterion: the ride-share model has the lower RMSE (1.227 vs.&nbsp;1.367 for public transit). Neither slope reached statistical significance (public transit: b = −0.048, R² = 0.153, p = .120; ride-share: b = −0.041, R² = 0.140, p = .139).</p>
</section>
<section id="rq2-jiangran-does-drivers-license-status-predict-communication-apprehension" class="level2">
<h2 class="anchored" data-anchor-id="rq2-jiangran-does-drivers-license-status-predict-communication-apprehension">3.2 RQ2 (Jiangran): Does driver’s-license status predict communication apprehension?</h2>
<p>Method: Using the same 12 PRCA items from FileC, this memo reverse-scored Q1, Q3, Q5, Q13, Q15, and Q18 and summed all 12 items into a composite CA_total. Respondents missing any CA item or Q20 (driver’s-license status) were excluded, leaving an analytic sample of N = 163 (138 “Yes,” 25 “No”). Group means were compared with an independent-samples t-test, with Levene’s test checking the equal-variance assumption.</p>
<div id="tbl-gu-license" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gu-license-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: CA_total by driver’s-license status.
</figcaption>
<div aria-describedby="tbl-gu-license-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Q20</th>
<th>n</th>
<th>Mean</th>
<th>SD</th>
<th>Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No</td>
<td>25</td>
<td>37.32</td>
<td>10.57</td>
<td>39.0</td>
</tr>
<tr class="even">
<td>Yes</td>
<td>138</td>
<td>41.43</td>
<td>12.12</td>
<td>43.5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-gu-license" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gu-license-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image7.png" class="img-fluid figure-img" width="283">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gu-license-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: CA_total by driver’s-license status.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Direct answer: Levene’s test supported equal variances (F = 0.963, p = .328); an independent-samples t-test found the difference not statistically significant, t(161) = 1.587, p = .114, Cohen’s d = 0.345, with the license-holder group trending toward slightly higher CA. The memo notes that this reverse-scoring scheme changed both the magnitude and the direction of the group difference relative to an unreversed composite it also considered (where the no-license group had trended higher, p = .069), and flags this as an open question about which items the PRCA key treats as reverse-worded.</p>
</section>
<section id="rq3-peiqi-what-visual-strategy-best-illustrates-the-catransportation-relationship" class="level2">
<h2 class="anchored" data-anchor-id="rq3-peiqi-what-visual-strategy-best-illustrates-the-catransportation-relationship">3.3 RQ3 (Peiqi): What visual strategy best illustrates the CA–transportation relationship?</h2>
<p>Method: This memo computed a total communication-apprehension score across the 12 items (Q1–Q6, Q13–Q18) after reverse-coding Q2, Q4, Q6, Q14, Q16, and Q17, and combined the transportation frequency and rides-per-day items into three outcomes: public-transportation use (Q26+Q27), ride-share use (Q28+Q29), and overall transportation use (their sum). Three scatterplots, each with a fitted linear trend line, were produced to visualize the relationship between apprehension and each outcome.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-li-public" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-li-public-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image6.png" class="img-fluid figure-img" width="884">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-li-public-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Communication apprehension vs.&nbsp;public-transportation use.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-li-rideshare" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-li-rideshare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image2.png" class="img-fluid figure-img" width="884">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-li-rideshare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Communication apprehension vs.&nbsp;ride-share use.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-li-overall" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-li-overall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image4.png" class="img-fluid figure-img" width="884">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-li-overall-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Communication apprehension vs.&nbsp;overall transportation use.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Answer: The memo concludes that scatterplots with fitted linear trend lines are an effective visual strategy: the trend line makes the overall direction immediately visible while the scatter conveys the amount of variability in the data. Across all three outcomes the visualizations suggest weak negative associations between communication apprehension and transportation use, most evident for overall transportation use, though the memo is explicit that these conclusions rest on visual inspection rather than a formal statistical test, and suggests nonparametric methods such as Spearman’s rank correlation as a next step.</p>
</section>
<section id="rq4-yuhao-model-comparison-for-predicting-public-transit-use" class="level2">
<h2 class="anchored" data-anchor-id="rq4-yuhao-model-comparison-for-predicting-public-transit-use">3.4 RQ4 (Yuhao): Model comparison for predicting public-transit use</h2>
<p>Method: Three nested models predicted public-transportation use frequency (PTRS): Model 1 uses total communication apprehension (CA12) alone; Model 2 uses the group (CA_group) and interpersonal (CA_interpersonal) subscales separately; Model 3 adds their interaction term. Of 255 participants, the memo reports 11 missing CA12 values, 5 missing CA_group, and 7 missing CA_interpersonal, leaving 244 complete cases (95.7%) used to fit and compare the three models by RMSE, with R² reported alongside.</p>
<div id="tbl-wang-descriptive" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wang-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Descriptive statistics reported (N = 244 complete cases).
</figcaption>
<div aria-describedby="tbl-wang-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Mean</th>
<th>SD</th>
<th>Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Public-transportation frequency (PTRS)</td>
<td>2.07</td>
<td>1.45</td>
<td>0–4</td>
</tr>
<tr class="even">
<td>Total CA (CA12)</td>
<td>28.9</td>
<td>11.33</td>
<td>12–60</td>
</tr>
<tr class="odd">
<td>Group CA (CA_group)</td>
<td>14.61</td>
<td>6.00</td>
<td>6–30</td>
</tr>
<tr class="even">
<td>Interpersonal CA (CA_interpersonal)</td>
<td>14.3</td>
<td>5.79</td>
<td>6–30</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-wang-rmse" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wang-rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: RMSE and R² comparison across the three models (sorted by RMSE).
</figcaption>
<div aria-describedby="tbl-wang-rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>RMSE</th>
<th>R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model 3 (group + interpersonal + interaction)</td>
<td>1.4005</td>
<td>0.0686</td>
</tr>
<tr class="even">
<td>Model 2 (group + interpersonal)</td>
<td>1.4006</td>
<td>0.0684</td>
</tr>
<tr class="odd">
<td>Model 1 (CA12 only)</td>
<td>1.4095</td>
<td>0.0566</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-wang-coefficients" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wang-coefficients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Regression coefficients for Models 1–3. Significance stars: * p &lt; .05, ** p &lt; .01, *** p &lt; .001.
</figcaption>
<div aria-describedby="tbl-wang-coefficients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 34%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Predictor</th>
<th>Estimate</th>
<th>SE</th>
<th>t</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Intercept</td>
<td>2.952</td>
<td>0.249</td>
<td>11.87</td>
<td>6.512e-26 ***</td>
</tr>
<tr class="even">
<td>1</td>
<td>CA12</td>
<td>−0.031</td>
<td>0.008</td>
<td>−3.81</td>
<td>1.757e-04 ***</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Intercept</td>
<td>2.941</td>
<td>0.248</td>
<td>11.87</td>
<td>6.879e-26 ***</td>
</tr>
<tr class="even">
<td>2</td>
<td>CA_group</td>
<td>−0.078</td>
<td>0.028</td>
<td>−2.76</td>
<td>6.209e-03 **</td>
</tr>
<tr class="odd">
<td>2</td>
<td>CA_interpersonal</td>
<td>0.019</td>
<td>0.029</td>
<td>0.64</td>
<td>5.258e-01</td>
</tr>
<tr class="even">
<td>3</td>
<td>Intercept</td>
<td>2.826</td>
<td>0.624</td>
<td>4.53</td>
<td>9.354e-06 ***</td>
</tr>
<tr class="odd">
<td>3</td>
<td>CA_group</td>
<td>−0.070</td>
<td>0.048</td>
<td>−1.46</td>
<td>1.45e-01</td>
</tr>
<tr class="even">
<td>3</td>
<td>CA_interpersonal</td>
<td>0.027</td>
<td>0.050</td>
<td>0.53</td>
<td>5.935e-01</td>
</tr>
<tr class="odd">
<td>3</td>
<td>CA_group × CA_interpersonal</td>
<td>0.000</td>
<td>0.002</td>
<td>−0.20</td>
<td>8.415e-01</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-wang-rmse" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wang-rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image3.jpg" class="img-fluid figure-img" width="498">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wang-rmse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: RMSE comparison across the three regression models. Lower RMSE indicates better predictive accuracy. (reproduced from Wang’s memo).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The memo notes that the figure it produced to visualize this comparison (“Figure 1: RMSE comparison across the three regression models”) was generated to an external file not included among the shared project files, so it is not reproduced here; the underlying RMSE and R² values are reported in Tables 5 and 6 above exactly as the memo presents them.</p>
<p>Direct answer: Model 3 gives the lowest RMSE (1.4005) and is identified as the best-performing model, narrowly ahead of Model 2 (RMSE = 1.4006) and Model 1 (RMSE = 1.4095). The memo also notes that the improvement from Model 1 to Model 2 is small (ΔR² = 0.0118) and the improvement from Model 2 to Model 3 is negligible, and suggests that the simpler Model 1 may be preferable on grounds of parsimony despite not having the numerically lowest RMSE. Across all three models, R² remains in the 5–7% range, which the memo interprets as showing that communication apprehension alone explains only a small portion of the variance in public-transportation use.</p>
</section>
<section id="rq5-jingyi-do-ca-and-transportation-use-differ-by-country" class="level2">
<h2 class="anchored" data-anchor-id="rq5-jingyi-do-ca-and-transportation-use-differ-by-country">3.5 RQ5 (Jingyi): Do CA and transportation use differ by country?</h2>
<p>Method: This memo concatenated PRCAProlificExport_FileA.csv and FileB.csv and merged the result with PRCAQualtricsExport_FileC.csv by matching each respondent’s typed Prolific ID (Q0) to their Prolific “Participant id.” The 12 PRCA items were coded on a 1–5 agreement scale (Q1, Q3, Q5, Q13, Q15, Q18 coded directly; Q2, Q4, Q6, Q14, Q16, Q17 coded on the reverse scale) and summed into a total CA score (“sum”). Public-transit and ride-share frequency (Q26, Q28) were coded 1–5 and rides-per-day (Q27, Q29) 1–4; their total across both modes formed “PTRS.” The memo visualized both measures by country of residence using violin plots (with an embedded box plot), first across all recruited countries and then restricted to the four countries with the largest samples (United States, United Kingdom, Ireland, Canada).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-jingyi-descriptive" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-jingyi-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image5.jpg" class="img-fluid figure-img" width="524">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-jingyi-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Descriptive statistics reported in Jingyi’s memo.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-jingyi-country" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-jingyi-country-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="media/image8.png" class="img-fluid figure-img" width="954">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-jingyi-country-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Communication apprehension (“sum”) and combined transportation use (“PTRS”) by country of residence, restricted to the four largest-sample countries.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Direct answer: The memo’s stated conclusion is descriptive: “we can see from the plot in different countries, CA and PTRS have some differences.” No formal statistical test (e.g., ANOVA) is reported in the memo to accompany this visual comparison.</p>
</section>
</section>
<section id="discussion-and-suggestions-for-next-steps" class="level1">
<h1>4. Discussion and Suggestions for Next Steps</h1>
<p>Read together, the five memos’ own reported findings suggest a generally negative relationship between communication apprehension and use of transportation modes that involve interacting with strangers: Chao’s memo finds ride-share use is predicted somewhat more accurately (lower RMSE) than public-transit use, and Peiqi’s memo’s scatterplots likewise show weak negative associations for both outcomes, most visible for overall transportation use. Yuhao’s memo, working with a much larger complete-case sample, similarly finds a small but statistically significant negative association between CA12 and public-transit use, and shows that splitting CA into group and interpersonal subscales adds only marginal predictive value over the single composite. Jiangran’s memo does not find a statistically significant relationship between driver’s-license status and CA, though the point estimate trends toward license-holders reporting somewhat higher apprehension under that memo’s reverse-scoring scheme. Jingyi’s memo shows country-level differences descriptively in a violin plot but does not report a formal test of whether those differences are statistically reliable.</p>
<p>As noted in Section 2.1, each memo’s analytic sample size and specific scoring choices (which items were reverse-coded, and whether the composite was a sum or a mean) differ from memo to memo, since each was produced independently. Readers comparing numbers across sections of this manuscript should keep that in mind; we have reported each memo’s own numbers, tables, and figures without altering them.</p>
<p>Limitations noted within the individual memos include: reliance on visual inspection rather than formal tests for the transportation-use scatterplots (Peiqi); a small non-license subgroup limiting power for the license-status comparison (Jiangran, n = 25); uniformly low R² values (5–15%) across every regression model reported (Chao, Yuhao), indicating CA is at most a minor predictor of transportation behavior; and, for the country comparison (Jingyi), highly unbalanced country sample sizes with no accompanying significance test.</p>
<p>Suggested next steps raised across the memos include: examining the group and interpersonal CA subscales separately rather than only the combined total (Jiangran); connecting license status to actual transportation use in a follow-up regression or mediation model (Jiangran); applying Spearman’s rank correlation or other nonparametric methods better suited to the ordinal transportation measures (Peiqi); testing alternative model specifications such as polynomial terms or transformations (Yuhao); and controlling for possible confounds such as age, car access (Q21), and urban vs.&nbsp;rural residence in a multivariate model (Jiangran).</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>McCroskey, J. C. (1982). An introduction to rhetorical communication (4th ed.). Prentice-Hall.</p>
<p>McCroskey, J. C. (n.d.). PRCA-24 (Personal Report of Communication Apprehension). Retrieved from https://www.jamescmccroskey.com/measures/prca24.htm</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>